-- Arxiu: 02_parkings.sql
-- Descripció: Aquest arxiu conté sentències (INSERT) per poblar inicialment la base de dades amb dades fictícies de prova.

-- 1. APARCAMENTS (15 aparcaments a Barcelona)
INSERT INTO aparcaments (
        id,
        nom,
        tipus,
        adreca,
        ciutat,
        codi_postal,
        latitud,
        longitud,
        capacitat_total,
        places_disponibles,
        tarifa_hora,
        tarifa_dia,
        horari_obertura,
        horari_tancament,
        obert_24h,
        caracteristiques,
        accessibilitat,
        carrega_electrica,
        videovigilancia,
        altura_maxima,
        estat,
        operador_id,
        verificat
    )
VALUES -- Centre de Barcelona
    (
        1,
        'Parking Plaça Catalunya',
        'cobert',
        'Plaça Catalunya, 9',
        'Barcelona',
        '08002',
        41.387428,
        2.169919,
        500,
        125,
        3.50,
        25.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "lavabo": true, "assist_24h": true}',
        TRUE,
        TRUE,
        TRUE,
        2.10,
        'actiu',
        3,
        TRUE
    ),
    (
        2,
        'Aparcament Rambla Catalunya',
        'subterrani',
        'Rambla de Catalunya, 15',
        'Barcelona',
        '08007',
        41.390205,
        2.163774,
        300,
        89,
        3.80,
        28.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "assist_24h": true}',
        TRUE,
        TRUE,
        TRUE,
        2.00,
        'actiu',
        3,
        TRUE
    ),
    (
        3,
        'Parking Passeig de Gràcia',
        'cobert',
        'Passeig de Gràcia, 63',
        'Barcelona',
        '08008',
        41.394699,
        2.163162,
        250,
        67,
        4.50,
        32.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "lavabo": true, "premium": true}',
        TRUE,
        TRUE,
        TRUE,
        2.10,
        'actiu',
        3,
        TRUE
    ),
    -- Sagrada Família
    (
        4,
        'Aparcament Sagrada Família',
        'subterrani',
        'Carrer de Mallorca, 401',
        'Barcelona',
        '08013',
        41.403569,
        2.174355,
        350,
        102,
        3.00,
        22.00,
        '07:00:00',
        '23:00:00',
        FALSE,
        '{"wifi": false, "assist_horary": true}',
        TRUE,
        FALSE,
        TRUE,
        2.10,
        'actiu',
        4,
        TRUE
    ),
    (
        5,
        'Parking Temple Expiatori',
        'aire_lliure',
        'Carrer de Sardenya, 311',
        'Barcelona',
        '08025',
        41.404824,
        2.175503,
        150,
        45,
        2.50,
        18.00,
        '08:00:00',
        '20:00:00',
        FALSE,
        '{"descobert": true}',
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'actiu',
        4,
        TRUE
    ),
    -- Port Olímpic i Platja
    (
        6,
        'Parking Port Olímpic',
        'aire_lliure',
        'Moll de Gregal, 15',
        'Barcelona',
        '08005',
        41.387134,
        2.198091,
        400,
        156,
        2.50,
        18.00,
        NULL,
        NULL,
        TRUE,
        '{"prop_platja": true, "wifi": false}',
        TRUE,
        TRUE,
        TRUE,
        2.00,
        'actiu',
        3,
        TRUE
    ),
    (
        7,
        'Aparcament Barceloneta',
        'carrer',
        'Passeig de Joan de Borbó, 88',
        'Barcelona',
        '08003',
        41.381542,
        2.189750,
        200,
        78,
        2.00,
        15.00,
        '09:00:00',
        '21:00:00',
        FALSE,
        '{"zona_blava": true, "prop_platja": true}',
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'actiu',
        NULL,
        TRUE
    ),
    -- Montjuïc i Fira
    (
        8,
        'Parking Fira de Barcelona',
        'cobert',
        'Avinguda de la Reina Maria Cristina, s/n',
        'Barcelona',
        '08004',
        41.371985,
        2.148568,
        800,
        423,
        2.80,
        20.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "esdeveniments": true}',
        TRUE,
        TRUE,
        TRUE,
        2.50,
        'actiu',
        4,
        TRUE
    ),
    (
        9,
        'Aparcament Plaça Espanya',
        'subterrani',
        'Plaça Espanya, 1',
        'Barcelona',
        '08014',
        41.375350,
        2.149050,
        450,
        189,
        3.20,
        24.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "lavabo": true}',
        TRUE,
        TRUE,
        TRUE,
        2.00,
        'actiu',
        3,
        TRUE
    ),
    -- Eixample
    (
        10,
        'Parking Hospital Clínic',
        'cobert',
        'Carrer Villarroel, 170',
        'Barcelona',
        '08036',
        41.390394,
        2.152899,
        300,
        91,
        3.50,
        26.00,
        NULL,
        NULL,
        TRUE,
        '{"hospital": true, "wifi": true}',
        TRUE,
        FALSE,
        TRUE,
        2.00,
        'actiu',
        4,
        TRUE
    ),
    (
        11,
        'Aparcament Diagonal',
        'subterrani',
        'Avinguda Diagonal, 442',
        'Barcelona',
        '08037',
        41.396350,
        2.153550,
        250,
        67,
        4.00,
        30.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "premium": true}',
        TRUE,
        TRUE,
        TRUE,
        2.10,
        'actiu',
        3,
        TRUE
    ),
    -- Gràcia
    (
        12,
        'Parking Vila de Gràcia',
        'cobert',
        'Carrer de la Mare de Déu dels Desemparats, 5',
        'Barcelona',
        '08012',
        41.401750,
        2.156850,
        200,
        56,
        3.00,
        22.00,
        '07:00:00',
        '22:00:00',
        FALSE,
        '{"wifi": false, "barri": true}',
        TRUE,
        FALSE,
        TRUE,
        2.00,
        'actiu',
        4,
        TRUE
    ),
    -- Sants
    (
        13,
        'Parking Sants Estació',
        'cobert',
        'Plaça dels Països Catalans, s/n',
        'Barcelona',
        '08014',
        41.379020,
        2.140310,
        600,
        234,
        2.80,
        20.00,
        NULL,
        NULL,
        TRUE,
        '{"wifi": true, "estacio_tren": true, "lavabo": true}',
        TRUE,
        TRUE,
        TRUE,
        2.20,
        'actiu',
        3,
        TRUE
    ),
    -- Les Corts
    (
        14,
        'Parking Camp Nou',
        'aire_lliure',
        'Carrer d''Aristides Maillol, s/n',
        'Barcelona',
        '08028',
        41.380896,
        2.122820,
        1000,
        567,
        5.00,
        40.00,
        '08:00:00',
        '23:00:00',
        FALSE,
        '{"esdeveniments_esportius": true, "gran_capacitat": true}',
        TRUE,
        FALSE,
        FALSE,
        NULL,
        'actiu',
        4,
        TRUE
    ),
    -- Zona Universitària
    (
        15,
        'Aparcament Zona Universitària',
        'aire_lliure',
        'Avinguda de la Diagonal, 686',
        'Barcelona',
        '08034',
        41.387550,
        2.115350,
        300,
        145,
        2.00,
        12.00,
        '07:00:00',
        '21:00:00',
        FALSE,
        '{"universitat": true, "estudiants": true}',
        FALSE,
        FALSE,
        FALSE,
        NULL,
        'actiu',
        NULL,
        TRUE
    ),
    -- Aparcaments sense disponibilitat per a tests
    (
        16,
        'Aparcament Full Center',
        'subterrani',
        'Carrer de Balmes, 10',
        'Barcelona',
        '08007',
        41.388900,
        2.166100,
        100,
        0,
        4.00,
        30.00,
        NULL,
        NULL,
        TRUE,
        '{"complet": true, "wifi": true}',
        TRUE,
        TRUE,
        TRUE,
        2.10,
        'actiu',
        3,
        TRUE
    ),
    (
        17,
        'Parking Mataró Centre',
        'cobert',
        'La Riera, 100',
        'Mataró',
        '08301',
        41.539200,
        2.444600,
        50,
        0,
        2.50,
        18.00,
        '08:00:00',
        '22:00:00',
        FALSE,
        '{"complet": true, "centre": true}',
        TRUE,
        FALSE,
        TRUE,
        2.40,
        'actiu',
        4,
        TRUE
    ),
    (
        18,
        'Parking TecnoCampus',
        'cobert',
        'Avinguda d\'Ernest Lluch, 32',
        'Mataró',
        '08302',
        41.528400,
        2.433800,
        300,
        150,
        2.00,
        15.00,
        NULL,
        NULL,
        TRUE,
        '{"universitat": true, "wifi": true}',
        TRUE,
        TRUE,
        TRUE,
        2.20,
        'actiu',
        3,
        TRUE
    ),
    (
        19,
        'Parking Port de Mataró',
        'aire_lliure',
        'Passeig Marítim, s/n',
        'Mataró',
        '08302',
        41.530500,
        2.449600,
        400,
        200,
        1.80,
        12.00,
        NULL,
        NULL,
        TRUE,
        '{"prop_platja": true, "wifi": false}',
        TRUE,
        FALSE,
        TRUE,
        NULL,
        'actiu',
        4,
        TRUE
    ),
    (
        20,
        'Parking Mataró Parc',
        'cobert',
        'Carrer de l\'Estrasburg, 5',
        'Mataró',
        '08304',
        41.554200,
        2.428500,
        1000,
        450,
        0.00,
        0.00,
        '09:00:00',
        '22:00:00',
        FALSE,
        '{"centre_comercial": true, "gratis": true}',
        TRUE,
        TRUE,
        TRUE,
        2.50,
        'actiu',
        3,
        TRUE
    );

-- 2. HISTÒRIC DE DISPONIBILITAT
INSERT INTO historic_disponibilitat (
        aparcament_id,
        places_disponibles,
        timestamp,
        font
    )
VALUES -- Parking Plaça Catalunya
    (1, 145, DATE_SUB(NOW(), INTERVAL 12 HOUR), 'sensor'),
    (1, 132, DATE_SUB(NOW(), INTERVAL 10 HOUR), 'sensor'),
    (1, 98, DATE_SUB(NOW(), INTERVAL 8 HOUR), 'sensor'),
    (1, 76, DATE_SUB(NOW(), INTERVAL 6 HOUR), 'sensor'),
    (1, 105, DATE_SUB(NOW(), INTERVAL 4 HOUR), 'sensor'),
    (1, 120, DATE_SUB(NOW(), INTERVAL 2 HOUR), 'sensor'),
    (1, 125, DATE_SUB(NOW(), INTERVAL 1 HOUR), 'sensor'),
    (1, 120, DATE_SUB(NOW(), INTERVAL 30 MINUTE), 'usuari'),
    -- Parking Sagrada Família
    (4, 145, DATE_SUB(NOW(), INTERVAL 8 HOUR), 'sensor'),
    (4, 120, DATE_SUB(NOW(), INTERVAL 6 HOUR), 'sensor'),
    (4, 95, DATE_SUB(NOW(), INTERVAL 4 HOUR), 'sensor'),
    (4, 102, DATE_SUB(NOW(), INTERVAL 2 HOUR), 'sensor'),
    -- Parking Port Olímpic
    (6, 200, DATE_SUB(NOW(), INTERVAL 10 HOUR), 'sensor'),
    (6, 167, DATE_SUB(NOW(), INTERVAL 6 HOUR), 'sensor'),
    (6, 156, DATE_SUB(NOW(), INTERVAL 2 HOUR), 'sensor'),
    -- Batch 2
    (1, 120, '2026-02-23 06:00:00', 'sistema'),
    (1, 98, '2026-02-23 08:30:00', 'sensor'),
    (1, 65, '2026-02-23 10:00:00', 'sensor'),
    (1, 45, '2026-02-23 12:30:00', 'sensor'),
    (1, 32, '2026-02-23 14:00:00', 'usuari'),
    (1, 58, '2026-02-23 18:00:00', 'sensor'),
    (1, 95, '2026-02-23 22:00:00', 'sensor'),
    (2, 75, '2026-02-23 07:00:00', 'sistema'),
    (2, 52, '2026-02-23 09:00:00', 'sensor'),
    (2, 28, '2026-02-23 13:00:00', 'sensor'),
    (2, 61, '2026-02-23 19:00:00', 'sensor'),
    (3, 200, '2026-02-23 06:30:00', 'sistema'),
    (3, 145, '2026-02-23 10:30:00', 'sensor'),
    (3, 89, '2026-02-23 14:30:00', 'usuari'),
    (3, 178, '2026-02-23 21:00:00', 'sensor'),
    (4, 48, '2026-02-23 08:00:00', 'sistema'),
    (4, 22, '2026-02-23 11:00:00', 'operador'),
    (4, 15, '2026-02-23 15:00:00', 'sensor'),
    (4, 39, '2026-02-23 20:00:00', 'sensor'),
    (5, 310, '2026-02-23 07:30:00', 'sistema'),
    (5, 201, '2026-02-23 11:30:00', 'sensor'),
    (5, 156, '2026-02-23 16:00:00', 'usuari'),
    (5, 278, '2026-02-23 23:00:00', 'sistema'),
    (16, 20, '2026-02-23 08:00:00', 'sistema'),
    (16, 5, '2026-02-23 09:00:00', 'sensor'),
    (16, 0, '2026-02-23 10:00:00', 'sensor'),
    (17, 10, '2026-02-23 08:30:00', 'sistema'),
    (17, 0, '2026-02-23 09:30:00', 'sensor');

-- 3. FOTOGRAFIES D'APARCAMENTS
INSERT INTO fotografies_aparcaments (
        aparcament_id,
        usuari_id,
        url,
        descripcio,
        verificada,
        ordre
    )
VALUES (1, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Vista general', TRUE, 1),
    (1, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Places d''aparcament', TRUE, 2),
    (2, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Interior il·luminat', TRUE, 1),
    (2, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Accés principal', TRUE, 2),
    (3, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Zones de seguretat', TRUE, 1),
    (3, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Planta subterrània', TRUE, 2),
    (4, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Entrada Sagrada Família', TRUE, 1),
    (4, 4, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Interior ampli', TRUE, 2),
    (5, 5, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Vigilància activa', TRUE, 1),
    (5, 5, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Zona de càrrega', TRUE, 2),
    (6, 6, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Port Olímpic', TRUE, 1),
    (6, 6, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Vistes al mar', TRUE, 2),
    (7, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Interior modern', TRUE, 1),
    (7, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Prop de la platja', TRUE, 2),
    (8, 4, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Zona centre', TRUE, 1),
    (8, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Fira de Barcelona', TRUE, 2),
    (9, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Places premium', TRUE, 1),
    (9, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Accés ràpid', TRUE, 2),
    (10, 4, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Accés 24h', TRUE, 1),
    (10, 4, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Seguretat', TRUE, 2),
    (11, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Senyalització clara', TRUE, 1),
    (11, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Diagonal', TRUE, 2),
    (12, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Estat impecable', TRUE, 1),
    (12, 4, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Vila de Gràcia', TRUE, 2),
    (13, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'A prop de l''estació', TRUE, 1),
    (13, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Sants Estació', TRUE, 2),
    (14, 4, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Zona residencial', TRUE, 1),
    (14, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Camp Nou', TRUE, 2),
    (15, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Sortida directa', TRUE, 1),
    (15, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Zona Universitària', TRUE, 2),
    (16, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Full Center', TRUE, 1),
    (16, 3, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Interior', TRUE, 2),
    (17, 4, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Mataró Centre', TRUE, 1),
    (17, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'La Riera', TRUE, 2),
    (18, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'TecnoCampus', TRUE, 1),
    (18, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Estudiants', TRUE, 2),
    (19, 4, '/storage/aparcaments/cataleg/parking_centre.jpg', 'Port de Mataró', TRUE, 1),
    (19, 4, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Exterior', TRUE, 2),
    (20, 3, '/storage/aparcaments/cataleg/parking_modern.jpg', 'Mataró Parc', TRUE, 1),
    (20, 3, '/storage/aparcaments/cataleg/parking_subterrani.jpg', 'Centre Comercial', TRUE, 2);
